In [1]:
import pandas as pd
import numpy as np

In [3]:
dataframe = pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

In [4]:
#Preguntas 

#Responde brevemente: 

#¿Quién produjo originalmente los datos? United Nations, World Population Prospects (2024)

#¿Qué organización los procesa para su utilización en Our World in Data? Our World in Data

#¿Qué representa la variable que analizarás? Un dataSet

In [5]:
dataframe.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [6]:
dataframe.shape

(38400, 5)

In [7]:
dataframe.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [8]:
dataframe.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [9]:
dataframe.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [10]:
dataframe.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [11]:
dataframe["Entity"].nunique()

256

In [12]:
#Preguntas 

#Responde brevemente: 

#¿Cuántas filas y columnas tiene el dataset? (38400, 5)

#¿Qué tipo de datos contiene la variable Year? int64

#¿Existen valores faltantes? SI

#¿Cuántas entidades diferentes contiene el dataset? 256

In [13]:
df_extraccion_filas = dataframe[dataframe["Year"] == 2020]
df_extraccion_filas.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN
519,Algeria,DZA,2020,747543.0,NaN
669,American Samoa,ASM,2020,-451.0,NaN

In [14]:
df_2020_mexico = dataframe[(dataframe["Year"] == 2020) & (dataframe["Entity"] == "Mexico")]
df_2020_mexico.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [15]:
df_mex = dataframe[((dataframe["Year"] >= 2006) & (dataframe["Year"] <= 2020)) & (dataframe["Entity"] == "Mexico")]
df_mex.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN
22257,Mexico,MEX,2008,1599930.0,NaN
22258,Mexico,MEX,2009,1625434.0,NaN
22259,Mexico,MEX,2010,1624178.0,NaN

In [16]:
df_tres_variables = df_mex[["Entity", "Year", "Annual change in population"]]
df_tres_variables.head()
df_tres_variables.dtypes

Entity                             str
Year                             int64
Annual change in population    float64
dtype: object

In [18]:
df_tres_variables.mean(numeric_only=True)

Year                           2.013000e+03
Annual change in population    1.399170e+06
dtype: float64

In [34]:
df_tres_variables.median(numeric_only=True)

Year                              2013.0
Annual change in population    1442162.0
dtype: float64

In [37]:
df_tres_variables.var(numeric_only=True)

Year                           2.000000e+01
Annual change in population    4.329210e+10
dtype: float64

In [39]:
df_tres_variables.std(numeric_only=True)

Year                                4.472136
Annual change in population    208067.544516
dtype: float64

In [40]:
df_tres_variables.min(numeric_only=True)

Year                              2006.0
Annual change in population    1036075.0
dtype: float64

In [41]:
df_tres_variables.max(numeric_only=True)

Year                              2020.0
Annual change in population    1625434.0
dtype: float64

In [ ]:
#Responde brevemente: 

#¿Cuál es el valor de la media? 2.013000e+03

#¿Cuál es el valor de la mediana? 2013.0

#¿Cuál es el valor de la desviación estándar?  4.472136

#¿Qué entidad presenta el valor mínimo y cuál el máximo? 2006.0 y 2020.0

In [44]:
dataframe.loc[:,["Entity", "Year"]]

            Entity  Year
0      Afghanistan  1951
1      Afghanistan  1952
2      Afghanistan  1953
3      Afghanistan  1954
4      Afghanistan  1955
...            ...   ...
38395     Zimbabwe  2096
38396     Zimbabwe  2097
38397     Zimbabwe  2098
38398     Zimbabwe  2099
38399     Zimbabwe  2100

[38400 rows x 2 columns]

In [52]:
dataframe.iloc[30:35 ,0:12]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
30,Afghanistan,AFG,1981,-1231727.0,NaN
31,Afghanistan,AFG,1982,-946206.0,NaN
32,Afghanistan,AFG,1983,-73395.0,NaN
33,Afghanistan,AFG,1984,272237.0,NaN
34,Afghanistan,AFG,1985,236633.0,NaN

In [54]:
dataframe.loc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [56]:
dataframe.loc[:, ["Entity", "Year", "Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [62]:
dataframe.loc[ df_2020_mexico.index , :]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [64]:
dataframe.iloc[0:6, :]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN
5,Afghanistan,AFG,1956,127322.0,NaN

In [67]:
dataframe.iloc[:, [0, 2, 3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [68]:
dataframe.iloc[0:4, 0:3]

        Entity Code  Year
0  Afghanistan  AFG  1951
1  Afghanistan  AFG  1952
2  Afghanistan  AFG  1953
3  Afghanistan  AFG  1954

In [76]:
df_apellido = dataframe[((dataframe["Year"] >= 2006) & (dataframe["Year"] <= 2023)) & (dataframe["Entity"] == "Mongolia")]
df_apellido

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22855,Mongolia,MNG,2006,21295.0,NaN
22856,Mongolia,MNG,2007,23215.0,NaN
22857,Mongolia,MNG,2008,26455.0,NaN
22858,Mongolia,MNG,2009,30902.0,NaN
22859,Mongolia,MNG,2010,36406.0,NaN
22860,Mongolia,MNG,2011,43444.0,NaN
22861,Mongolia,MNG,2012,50280.0,NaN
22862,Mongolia,MNG,2013,56424.0,NaN
22863,Mongolia,MNG,2014,61154.0,NaN
22864,Mongolia,MNG,2015,63487.0,NaN
22865,Mongolia,MNG,2016,64287.0,NaN
22866,Mongolia,MNG,2017,63556.0,NaN
22867,Mongolia,MNG,2018,63343.0,NaN
22868,Mongolia,MNG,2019,64404.0,NaN
22869,Mongolia,MNG,2020,58668.0,NaN
22870,Mongolia,MNG,2021,48890.0,NaN
22871,Mongolia,MNG,2022,46339.0,NaN
22872,Mongolia,MNG,2023,45923.0,NaN

In [81]:
media = df_apellido.mean(numeric_only=True)
mediana = df_apellido.median(numeric_only=True)
varianza = df_apellido.var(numeric_only=True)
Desviacion = df_apellido.std(numeric_only=True)
Minimo = df_apellido.min(numeric_only=True)
Maximo = df_apellido.max(numeric_only=True)
print(media)
print(mediana)
print(varianza)
print(Desviacion)
print(Minimo)
print(Maximo)

Year                                     2014.500000
Annual change in population             48248.444444
Annual population change (Projected)             NaN
dtype: float64
Year                                     2014.5
Annual change in population             49585.0
Annual population change (Projected)        NaN
dtype: float64
Year                                    2.850000e+01
Annual change in population             2.270889e+08
Annual population change (Projected)             NaN
dtype: float64
Year                                        5.338539
Annual change in population             15069.469354
Annual population change (Projected)             NaN
dtype: float64
Year                                     2006.0
Annual change in population             21295.0
Annual population change (Projected)        NaN
dtype: float64
Year                                     2023.0
Annual change in population             64404.0
Annual population change (Projected)        NaN
dtype: float64

In [83]:
import sys 
print("Python:", sys.version) 

print("Pandas:", pd.__version__) 

print("NumPy:", np.__version__)

Python: 3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.5
NumPy: 2.5.2